Insight/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Insight.Controllers
{
    public class MessageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Insight/Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Insight.Models;
using Insight.Data;
using Insight.Ajax;
using Newtonsoft.Json;

namespace Insight.Controllers
{
    public class SkillController : Controller
    {
        private readonly InsightContext _context;

        //Constructor
        public SkillController(InsightContext context)
        {
            //Get DB context
            _context = context;
        }

        /// <summary>
        /// Return the Skill listing page.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            List<Skill> allSkills = await _context.Skill
                .Include(i => i.SkillTopics)
                .Include(i => i.Creator)
                .ToListAsync();
            
            ViewBag.openingLines = new string[] {
                "Go on, you know you want to.",
                "Arm yourself with knowledge.",
                "Delve into the depths.",
                "We're sure you'll find something useful.",
                "Browse to your heart's content.",
                "Please - we insist." };
            return View(allSkills);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="skillID"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetTopicAjax(int skillID)
        {
            Skill thisSkill = await _context.Skill
                .Include(i => i.SkillTopics)
                .Where(i => i.ID == skillID)
                .SingleAsync();
            SkillAndTopicsAjax returnData = new SkillAndTopicsAjax(thisSkill);

            return Json(returnData);
        }
    }
}

Insight/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Insight.Controllers
{
    public class SubscriptionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Insight/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Insight.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Insight/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Insight</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <!--Styling-->
    @RenderSection("Styles", required: false)
</head>
<body>
    <!--Main site menu-->
    <div id="site_Menu" data-isClosed="1">
        <div id="site_MenuLeft">
            <a asp-controller="User" asp-action="Index">
                <div class="site_MenuOption">My Profile</div>
            </a>
            <a asp-controller="Subscription" asp-action="Index">
                <div class="site_MenuOption">My Subscriptions</div>
            </a>
            <a asp-controller="Home" asp-action="Index">
                <div class="site_MenuOption">Home</div>
            </a>
            <a asp-controller="Message" asp-action="Index">
                <div class="site_MenuOption">My Messages</div>
            </a>
            <a asp-controller="Skill" asp-action="Index">
                <div class="site_MenuOption lastItem">Explore</div>
            </a>
        </div>
    </div>

    <!--Navbar-->
    <div id="site_Navbar" onclick="SwitchMenu()">
        <p>InSight</p>
    </div>
    <br /><br /><br />
    <!--Page content-->
    @RenderBody()

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <!--Scripts-->
    @RenderSection("Scripts", required: false)
</body>
</html>